### ISSUE TITLE
Code 477 no matter which key

### ISSUE THREAD

**Issue by A-w-K** [nikeee/node-jodel-api#10]
I tried every key documented in Keys.MD - even the old Wodel configuration with WindowsJodelConfig but still I get the 477 error every time.
Is the HMAC generation up-to-date?

**Comment by nikeee** [comment]
They seem to have invalidated all keys *or* changed the signing procedure. Does https://bitbucket.org/cfib90/ojoc work for you? Just to make sure this isn't an implementation bug in jodel-api.

**Comment by A-w-K** [comment]
Thanks! Let me know if I can help somehow

**Comment by nikeee** [comment]
Have a look at [this issue](https://bitbucket.org/cfib90/ojoc/issues/14/keep-up-with-hmac-key-changes). 
For now, you may use the one provided in [this PR](https://bitbucket.org/cfib90/ojoc/pull-requests/8/added-hmac-key-for-4470/diff). However, you have to extract the key by yourself on long term since it changes every update and older ones get invalidated from time to time.
