### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by asd34234Y** [nikeee/node-jodel-api#19]
Why do you even bother to create an unoffical api? It will just get broken after some updates and ruin the comminity

**Comment by nikeee** [comment]
Well, it was created primarily to allow other clients (CLI, etc) to connect to the services. I used as as a read-only access to do stuff with that and I wasn't using my phone that much, so I needed other means of reading that content. Someone was going to build 3rd party APIs anyway.

Other people built services like automatic weather forecasts for each day, which large parts of the community really liked.

And yes, it is most likely broken by now. I'm not using Jodel anymore as I'm annoyed by their dark practices (intentionally sending notifications that can't be turned off without turning _all_ off). I assume that they did this because their user base is most likely shrinking by now.
I'll keep this repo non-archived because maybe someone wants to fix stuff in here or doesn't want to start from scratch.

If they don't like this, they're free to reach out to me, so we can see what we can do about this.
